In [136]:
import pandas as pd
import numpy as np
df=pd.read_csv('/opt/app-root/src/base_data.csv')
import warnings
warnings.filterwarnings('ignore')

In [141]:
df=df.drop(['Unnamed: 0.1'],axis=1)

In [142]:
df.shape

(4510, 25)

In [143]:
#!pip install sklearn-relief==1.0.0b2

In [144]:
df

,gid,accident_cnt,geometry,coordinates,coord_cent,geo_cent,car_cnt,total_pop,kid_pop,prod_pop,...,num_sign,speed_dump,num_cctv,bus_station,num_sports,academy,통학구역여부,num_crosswalk,lights,인도여부
0,다사551085,0,MULTIPOLYGON (((126.9942156468143 37.174182357...,"[[126.99421564681425, 37.17418235770403], [126...","[126.99477586013964, 37.174635450576154]",POINT (126.9947758601396 37.17463545057615),0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,1
1,다사551086,0,MULTIPOLYGON (((126.9942096381632 37.175083738...,"[[126.99420963816323, 37.17508373885349], [126...","[126.9947698580453, 37.17553683173449]",POINT (126.9947698580453 37.17553683173449),0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,1
2,다사551087,0,MULTIPOLYGON (((126.9942036292448 37.175985119...,"[[126.99420362924478, 37.17598511986466], [126...","[126.99476385568379, 37.17643821275453]",POINT (126.9947638556838 37.17643821275453),0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,1
3,다사551088,0,MULTIPOLYGON (((126.9941976200589 37.176886500...,"[[126.9941976200589, 37.17688650073755], [126....","[126.99475785305518, 37.17733959363628]",POINT (126.9947578530552 37.17733959363628),0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,1
4,다사552085,0,MULTIPOLYGON (((126.9953420754172 37.174187160...,"[[126.99534207541716, 37.174187160436155], [12...","[126.9959022955662, 37.174640248032546]",POINT (126.9959022955662 37.17464024803255),0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4505,다사646052,0,MULTIPOLYGON (((127.1013836908642 37.144844715...,"[[127.10138369086417, 37.14484471529977], [127...","[127.10194433397315, 37.14529730643224]",POINT (127.1019443339732 37.14529730643224),0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4506,다사646053,0,MULTIPOLYGON (((127.1013789603587 37.145746114...,"[[127.10137896035867, 37.145746114265314], [12...","[127.10193961004353, 37.146198705390276]",POINT (127.1019396100435 37.14619870539028),0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4507,다사647050,0,MULTIPOLYGON (((127.1025191345573 37.143045698...,"[[127.10251913455733, 37.14304569816435], [127...","[127.10307977130084, 37.143498284025306]",POINT (127.1030797713008 37.14349828402531),0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4508,다사647051,0,MULTIPOLYGON (((127.1025144178335 37.143947097...,"[[127.10251441783353, 37.14394709752859], [127...","[127.10307506115258, 37.144399683381856]",POINT (127.1030750611526 37.14439968338186),0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4509,다사647052,0,MULTIPOLYGON (((127.1025097008998 37.144848496...,"[[127.10250970089983, 37.144848496754896], [12...","[127.1030703507947, 37.145301082600476]",POINT (127.1030703507947 37.14530108260048),0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [145]:
df['accident_cnt'].value_counts()

0     4165
1      238
2       63
3       25
5        7
4        7
6        3
7        1
10       1
Name: accident_cnt, dtype: int64

In [146]:
#이진 분류 문제로 변경
ac2=df[df['accident_cnt']==2].copy()
ac3=df[df['accident_cnt']==3].copy()
ac4=df[df['accident_cnt']==4].copy()
ac5=df[df['accident_cnt']==5].copy()
ac6=df[df['accident_cnt']==6].copy()
ac7=df[df['accident_cnt']==7].copy()
ac10=df[df['accident_cnt']==10].copy()

In [147]:
#데이터 증식 후 이진 변환 문제로 바꿔주기
data=pd.concat([df,ac2,ac3,ac4,ac5,ac6,ac7,ac10])

In [148]:
data['target']=np.where(data['accident_cnt']>0,1,0)
data.drop(['accident_cnt','geometry','coordinates','gid'],axis=1,inplace=True)

In [150]:
data.to_csv('relif_data.csv')

In [96]:
data['target'].value_counts()

0    4165
1     452
Name: target, dtype: int64

# Relief algorithm
- 파이썬에서는 그냥 변수 선택까지만 되고 plot으로 그릴 수가 없음
- R로 그려서 변수 선택 
- RelifeF와 relief의 차이점 또한 고려해봐야 한다
![nn](relief.png)

In [125]:
#relief 알고리즘
r = rf.Relief(
    n_features=10 # Choose the best 3 features
)
transformed_matrix = r.fit_transform(
    data.iloc[:,2:].values,
    data['target'].values
)

In [133]:
data.to_csv('relif_data.csv')

In [115]:
#relif - F 알고리즘
import sklearn_relief as rf
from ReliefF import ReliefF

fs = ReliefF(n_neighbors=20, n_features_to_keep=10)

#values함수로 array 변환 거쳐야 함
x_train=r.fit_transform(data.iloc[:,2:].values,data['target'].values)


x_train